### ISSUE TITLE
 error:bad Go source code was generated: 41:75: expected type, found '.'

### ISSUE THREAD

**Issue by alaibe** [asim/protoc-gen-micro#51]
Hey,
When I generate the the go source code with an import I get this error:
` error:bad Go source code was generated: 41:75: expected type, found '.'`

And here is the line 41:
```
func (c *oauthService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*.UserResponse, error){
```

Also for reference here are the proto file:
```
syntax = "proto3";

package people;

import "identity.proto";

service Oauth {
	rpc Login(LoginRequest) returns (UserResponse);
}
```
```
syntax = "proto3";

package people;
...
message UserResponse {
        uint64 id = 1;
	string email = 2;
        string name = 3;
}
```

Also I have the same error if the package are the same or not

Is it something I am doing wrong?
Thx

**Comment by xuuj** [comment]
same

**Comment by xuuj** [comment]
I use "option go_package" to specify file path, it woks now.

**Comment by asim** [comment]
This package is deprecated
