### ISSUE TITLE
protoc-gen-micro: program not found or is not executable

### ISSUE THREAD

**Issue by lagorsse** [asim/protoc-gen-micro#62]
Hi,

protoc --proto_path=$GOPATH/src:. --micro_out=. --go_out=. greeter.proto
protoc-gen-micro: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--micro_out: protoc-gen-micro: Plugin failed with status code 1.

my path is set like this
export PATH=$PATH:$GOPATH/bin:$GOPATH

I think the plugin isn't build, it should end up in the bin folder but it's not there while the micro src code is well located but not as a v2.

My go get does that and it doesn't seems normal.
go get github.com/micro/protoc-gen-micro/v2
package github.com/micro/protoc-gen-micro/v2: cannot find package "github.com/micro/protoc-gen-micro/v2" in any of:
	/usr/local/Cellar/go/1.13.7/libexec/src/github.com/micro/protoc-gen-micro/v2 (from $GOROOT)
	/Users/julien/work/src/github.com/micro/protoc-gen-micro/v2 (from $GOPATH) 

If I removed the v2 it works and then the protoc works but I fear I am using the wrong version.

**Comment by AdolphKevin** [comment]
you can try `which protoc-gen-micro`, if no result,then config system path

**Comment by AdolphKevin** [comment]
you need git clone protoc-gen-micro, build,config system path

1.`git clone https://github.com/micro/protoc-gen-micro.git` into $GOPATH/src/github.com/micro/
2.`cd $GOPATH/src/github.com/micro/` exce `go build`
3. 
insert  `export PROTOC_GEN_MICRO=$GOPATH/src/github.com/micro/protoc-gen-micro` into `~/.bash_profile`
and `PATH=`append`:$PROTOC_GEN_MICRO`
4.source `~/.bash_profile`
