### ISSUE TITLE
Missing 'go_package' option

### ISSUE THREAD

**Issue by nicocesar** [asim/protoc-gen-micro#67]
there is an annoying warning with a microservice that created from scratch  using "micro new "

How can I add a go_package option to the templates used by new  command

```
$ make build
protoc --proto_path=/home/nico/go/src:. --micro_out=. --go_out=. proto/tokenplay/tokenplay.proto
2020/03/26 13:02:22 WARNING: Missing 'go_package' option in "proto/tokenplay/tokenplay.proto", please specify:
	option go_package = "proto/tokenplay";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

```

**Comment by skyjia** [comment]
meet the same issue

**Comment by said-saifi** [comment]
In your .proto file add the below

`option go_package = ".;<gopkg>" ;`

replace `<gopkg>` by your go pkg name.

**Comment by nicocesar** [comment]
I know the fix, but `micro new` should not come out with bugs out of the box.

**Comment by asim** [comment]
This repo is deprecated. Please make any relevant comments in micro/micro
