### ISSUE TITLE
go run main.go ,error: What is the problem？

### ISSUE THREAD

**Issue by Xuzan9396** [asim/protoc-gen-micro#69]
# command-line-arguments
service/account/main.go:22:49: cannot use service.Server() (type "github.com/micro/go-micro/server".Server) as type "github.com/micro/go-micro/v2/server".Server in argument to go_micro_service_user.RegisterUserServiceHandler:
	"github.com/micro/go-micro/server".Server does not implement "github.com/micro/go-micro/v2/server".Server (wrong type for Handle method)
		have Handle("github.com/micro/go-micro/server".Handler) error
		want Handle("github.com/micro/go-micro/v2/server".Handler) error

![image](https://user-images.githubusercontent.com/24741439/78681525-6eea0900-791f-11ea-83a7-cef8d98085ca.png)

**Comment by asim** [comment]
Please use v2 imports?

**Comment by Xuzan9396** [comment]
3q, I switched back to the v1 version
