### ISSUE TITLE
LICENSE not present at the root of the repository

### ISSUE THREAD

**Issue by BharathB23** [asim/protoc-gen-micro#73]
The source file contains a license header, but it would be better if a license file exists at the repository root level.

github documentation regarding licensing says, if LICENSE is missing, the project can't be used freely. Below is the excerpt

```
You're under no obligation to choose a license. However, without a license, the default copyright laws apply, 
meaning that you retain all rights to your source code and no one may reproduce, distribute, or create 
derivative works from your work. If you're creating an open source project, we strongly encourage you 
to include an open source license.
```

Please add a suitable license file.

Thanks in advance.

**Comment by asim** [comment]
This repo is deprecated
